site_name: Computer-Assisted Image Clustering

nav:
  - Start: index.md
  - Instructions:
    - Instructions: instructions/instructions.md
  - Clusterings:
    - Clusterings: clusterings/clusterings.md
  - Extras:
    - Extras: extras/extras.md


theme:
  name: material
  greetings: Welcome to 
  font:
    # text: Lato
    code: JetBrains Mono

  logo: assets/polarvis_logo.png

  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.annotate
    - content.tabs.link

  custom_dir: mkdocs_polar/
#
# extra_css:
#   - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
   - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        num_workers: 8
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
